Provide Scope Edit Capability
digi-serve/ab_migration_manager pull request #4
Opened 2023-03-24 09:04 UTC by jamesduncan

2023-03-27 02:48 UTC, nh758 approved these changes

2023-03-28 00:12 UTC, Hiro-Nakamura requested changes
Just update the comment and you're good to go.

2023-03-28 00:12 UTC, Hiro-Nakamura commented on patches/20230324.sql
> +# 1) Insert the Switcheroo Role
Is this what you are doing here?

2023-03-28 00:12 UTC, Hiro-Nakamura commented on patches/20230324.sql
> +ON DUPLICATE KEY UPDATE
Nice SQL here ...

2023-03-28 04:16 UTC, jamesduncan commented on patches/20230324.sql
> +# 1) Insert the Switcheroo Role
Haha! Thanks...changing it now.

2023-03-28 04:49 UTC, merged